### ISSUE TITLE
Dell recovery shows an "Operation was cancelled" prompt

### ISSUE THREAD

**Issue by fourdollars** [superm1/dell-recovery#1]
[Steps]
1. Install image
2. Launch Dash and enter "Dell"
3. Select Dell recovery tool
4. Select "Restore System" and enter password
5. A shut down prompt will pop up, with an exception prompt seen in the background.
6. Close the purple shutdown prompt and check the exception prompt that is displayed

[Expected result]
No exception prompt should be seen

[Actual result]
An exception prompt is seen after step 4 and can be brought to foreground after doing step 6

Note: If user directly selects reboot in the shutdown prompt and ignore the exception prompt, Dell recovery can still be completed.

[Test details]
machine: Constantine i7 EVT board, CONS-DVT1-C2 (i5) FORD-DVT1-C2
image: somerville-xenial-amd64-iso-hybrid-20160303-3.iso

**Comment by fourdollars** [comment]
This exception is triggered when doing "iface.Reboot()" in Dell/recovery_gtk.py.

**Comment by fourdollars** [comment]
When I executed http://paste.ubuntu.com/15390284/, it returns "org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Operation was cancelled".

**Comment by superm1** [comment]
Hmm, this makes me question if https://github.com/superm1/dell-recovery/commit/1e316510627e44c189902bd74ab65bcfed552a83 was even correct to change.  Reviewing gnome-session's changelog they are still carrying 95_dbus_request_shutdown.patch which adds RequestReboot functionality.

This may have actually been an unintentional regression in gnome-session then.  If you change your pastebin to:

```
#! /usr/bin/env python3

def main():
    import dbus
    bus = dbus.SessionBus()
    obj = bus.get_object('org.gnome.SessionManager', '/org/gnome/SessionManager')
    iface = dbus.Interface(obj, 'org.gnome.SessionManager')
    try:
        iface.RequestReboot()
    except dbus.DBusException as msg:
        print(msg)

if __name__ == '__main__':
    main()
```
Is it still failing?

**Comment by fourdollars** [comment]
If I changed it to "iface.RequestReboot()", it returns "org.freedesktop.DBus.Error.UnknownMethod: Method RequestReboot is not implemented on interface org.gnome.SessionManager" on Ubuntu 16.04.

**Comment by superm1** [comment]
FWIW
```#gnome-session-quit --reboot```

Has the same errors but they're not critical and cause problem.  I'll rather just call that instead.
